version: 2
jobs:
  build:
    docker:
      - image: node:8.10
    steps:
      - checkout

      - run:
          name: Install required packages
          command: apt-get update && apt-get install -y zip

      - restore_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}

      - run:
          name: Print versions
          command: node --version && yarn --version

      - run:
          name: Install node packages
          command: yarn install

      - save_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run eslint
          command: yarn test:lint

      - run:
          name: Run tests
          command: yarn test:unit

      - run:
          name: Build package
          command: yarn package

      - store_artifacts:
          path: package.zip
